/* minimapTiles.jsx
   Exports all the textures needed to show the local map world
   For the game Settlers & Warlords
*/

export const minimapTiles = [
    { id: 0, name: "Air", img: "air.png", desc: "Open air. Nice to breathe, but not nice to stand on", category: "gas", walkLag: 50 },
    { id: 1, name: "Dirt", img: "dirt.png", desc: "Exposed dirt", category: "ground", walkLag: 15 },
    { id: 2, name: "Rock", img: "rock.png", desc: "Exposed rock", category: "ground", walkLag: 7 },
    { id: 3, name: "Bent Grass", img: "bentgrass.png", desc: "Bent grass, it grows everywhere", category: "grass", walkLag: 12 },
    {
        id: 4,
        name: "Switch Grass",
        img: "switchgrass.png",
        desc: "Switchgrass, grows very tall",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 5,
        name: "Tree Branches",
        img: "treebranches.png",
        desc: "Branches of trees in the air",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 6,
        name: "Wheat Grass",
        img: "wheatgrass.png",
        desc: "Wheat. Tasteful grains for a variety of uses",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 7,
        name: "Oat Grass",
        img: "oatgrass.png",
        desc: "Oat. Hearty grains for many purposes",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 8,
        name: "Rye Grass",
        img: "ryegrass.png",
        desc: "Rye. Makes a sour tasting bread",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 9,
        name: "Barley Grass",
        img: "barleygrass.png",
        desc: "Barley. A nutty grain",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 10,
        name: "Millet Grass",
        img: "milletgrass.png",
        desc: "Millet. It's good for you",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 11,
        name: "Leaf Floor",
        img: "leafyfloor.png",
        desc: "Leaves fallen from a tree",
        category: "grass",
        walkLag: 14,
    },
    {
        id: 12,
        name: "Maple Tree",
        img: "maplebark.png",
        desc: "Maple trees. Its sap is useful for syrups",
        category: "tree",
        walkLag: 10, // walking on top of wood should be fairly fast
    },
    {
        id: 13,
        name: "Birch Tree",
        img: "birchbark.png",
        desc: "Birch trees. Its bark is good for making ropes",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 14,
        name: "Oak Tree",
        img: "oakbark.png",
        desc: "Oak trees. Provides acorns - edible in a pinch",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 15,
        name: "Mahogany Tree",
        img: "mohaganybark.png",
        desc: "Mahogany trees. Provides lots of shade",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 16,
        name: "Pine Tree",
        img: "pinebark.png",
        desc: "Pine trees. Green year-round, and provides pinecones",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 17,
        name: "Cedar Tree",
        img: "cedarbark.png",
        desc: "Cedar trees. Grows tall and straight",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 18,
        name: "Fir Tree",
        img: "firbark2.png",
        desc: "Fir trees. Strong trees that make lots of sticks",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 19,
        name: "Hemlock Tree",
        img: "hemlockbark.png",
        desc: "Hemlock trees. Grows tall in tight clusters",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 20,
        name: "Cherry Tree",
        img: "cherrybark.png",
        desc: "Cherry trees. Makes a tart fruit, good for many dishes",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 21,
        name: "Apple Tree",
        img: "applebark.png",
        desc: "Apple trees. Delicious fruits that everyone enjoys",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 22,
        name: "Pear Tree",
        img: "pearbark.png",
        desc: "Pear trees. Tasty fruits that excel in colder climates",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 23,
        name: "Orange Tree",
        img: "applebark.png",
        desc: "Orange trees. Sweet fruits that enjoy warmer climates",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 24,
        name: "Hawthorn Tree",
        img: "hawthornbark.png",
        desc: "Hawthorn trees. It seems to pulse with extra energy",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 25,
        name: "Dogwood Tree",
        img: "dogwoodbark.png",
        desc: "Dogwood trees. You wouldn't think this could grow here, but it's determined",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 26,
        name: "Locust Tree",
        img: "locustbark.png",
        desc: "Locust trees. It seems to have an extra glow in the sunlight",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 27,
        name: "Juniper Tree",
        img: "juniperbark.png",
        desc: "Juniper trees. It seems to come alive at night",
        category: "tree",
        walkLag: 10,
    },
    {
        id: 28,
        name: "Barren Rock",
        img: "rock.png",
        desc: "Barren rock. Easy source of stone materials and building on",
        category: "ground",
        walkLag: 7,
    },
    {
        id: 29,
        name: "Desert Sands",
        img: "desert.jpg",
        desc: "Desert sands. Hot, dusty and hard to build on",
        category: "ground",
        walkLag: 17,
    },
    {
        id: 30,
        name: "Still Water",
        img: "swampwater.png",
        desc: "Sitting water. Lots of life grows in it, but drinking it will make you sick",
        category: "liquid",
        walkLag: 25,
    },
    { id: 31, name: "Lava", img: "lava.png", desc: "Hot lava! Very dangerous, even from a distance", category: "liquid", walkLag: 70 },
    { id: 32, name: "Ice", img: "ice.png", desc: "Slick ice. Very cold", category: "ground", walkLag: 14 },
    { id: 33, name: "Snow", img: "snow.png", desc: "Snowed-over ground. Very cold", category: "ground", walkLag: 20 },
    {
        id: 34,
        name: "Water",
        img: "water.png",
        desc: "Flowing water through a stream",
        category: "liquid",
        walkLag: 25,
    },
    {
        id: 35,
        name: "Swamp",
        img: "swampgrass.png",
        desc: "Wet grounds. Some grass, mostly water",
        categoroy: "ground",
        walkLag: 25,
    },
    {
        id: 36,
        name: "Cliff",
        img: "cliffside.png",
        desc: "Rugged cliff. Don't get too close to the edge",
        category: "ground",
        walkLag: 12,
    },
    {
        id: 37,
        name: "Rubble",
        img: "rockrubble.png",
        desc: "Creek-wide rubble. Lots of tiny rocks that the water washed in",
        category: "ground",
        walkLag: 17,
    },
    {
        id: 38,
        name: "Bank",
        img: "creekbank.png",
        desc: "Creek bank. The streams are slowly eroding this wall",
        category: "ground",
        walkLag: 16,
    },
    {
        id: 39,
        name: "Carrots",
        img: "wildcarrot.jpg",
        desc: "Wild carrots. An excellent vegetable",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 40,
        name: "Potatoes",
        img: "wildpotato.jpg",
        desc: "Wild potatoes. A very filling vegetable",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 41,
        name: "Tomatoes",
        img: "wildtomato.png",
        desc: "Wild tomatoes. Useful for many cooking recipes",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 42,
        name: "Turnips",
        img: "wildturnip.png",
        desc: "Wild turnips. A nutritious vegetable",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 43,
        name: "Peanuts",
        img: "wildpeanut.png",
        desc: "Wild peanuts. A tasty snack",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 44,
        name: "Maize",
        img: "wildmaize.png",
        desc: "Wild Maize - also known as corn. Has many uses",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 45,
        name: "Beans",
        img: "wildbean.png",
        desc: "Wild beans. A very filling vegetable",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 46,
        name: "Onions",
        img: "wildonion.png",
        desc: "Wild onion. A sharp taste on its own, but great with other foods",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 47,
        name: "Broccoli",
        img: "wildbroccoli.png",
        desc: "Wild broccoli. A good vegetable",
        category: "grass",
        walkLag: 12,
    },
    { id: 48, name: "Pumpkins", img: "wildpumpkin.png", desc: "Wild pumpkin", category: "grass", walkLag: 25 },
    {
        id: 49,
        name: "Mushrooms",
        img: "wildmushroom.png",
        desc: "Wild mushrooms. Some edible, some deadly",
        category: "grass",
        walkLag: 12,
    },
    {
        id: 50,
        name: "Grass",
        img: "emptygrass.jpg",
        desc: "Short grassy space, well managed",
        category: "grass",
        walkLag: 12,
    },
    { id: 51, name: "Farmland", img: "farmplot.png", desc: "Active farm space", category: "grass", walkLag: 25 },
    {
        id: 52,
        name: "Gravel",
        img: "gravel.png",
        desc: "Flat gravel surface. Won't turn into a muddy mess in the rain",
        category: "ground",
        walkLag: 10,
    },
];
